server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xs2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=PST
    username: root
    password: 123

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml