server:
  port: 8080


bdk:
  datasource:
    host: localhost
    username: root
    password: 123

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true