server:
  port: ${server.port:8081}
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${bdk.datasource.host}/xs2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=PST
    username: root
    password: 123

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true